apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-webapitesting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-webapi-app
  template:
    metadata:
      labels:
        app: lms-webapi-app
    spec:
      containers:
      - name: lms-webapidockerrepo
        image: igetit2testcontainerregistry.azurecr.io/lms-abc
	  imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: lms-webapi-app-svc  
spec:
  selector:
    app: lms-webapi-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
type: LoadBalancer