apiVersion: v1
kind: Namespace
metadata:
  name: dev
---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: abi-deployment
  namespace: dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abi-deployment
  template:
    metadata:
      labels:
        app: abi-deployment
    spec:
      containers:
      - name: abi-deployment
        image: igetit2testcontainerregistry.azurecr.io/fronted:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: TITLE
          value: "IGETITV2-API"
      imagePullSecrets:
      - name: igetit2
---
apiVersion: v1
kind: Service
metadata:
  name: abi-service 
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: abi-deployment
